<?php
ob_start();
session_start();
// print   $_SERVER["REQUEST_URI"];
extract($_POST);extract($_GET);extract($_REQUEST);
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-874" />
<title>Untitled Document</title>
</head>
 
<body>
 <?php
 
include_once( '../../Connections/conf.php' ); 
include_once( 'php-ofc-library/open-flash-chart.php' );
srand((double)microtime()*1000000);


$bar_red = new bar_3d( 75, '#D54C78' );
$bar_red->key( 'Online  ', 20 );

    $query_Recordset1 = "SELECT *   FROM gp_login   ";
$Recordset1 = mysql_query($query_Recordset1, $connect_db) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
 
 
   do {  
     $daygp=$row_Recordset1[daygp];	  	 	 	 	 	 	 
	$mountgp	=$row_Recordset1[mountgp];	    	 	 	 	 
	$year_gp	 	=$row_Recordset1[year_gp];	   	 	 	 	 	 	 
	$dayep	  =$row_Recordset1[dayep];	  	 	 	 	 	 	 
	$mountep	 	 =$row_Recordset1[mountep];	  	 	 	 	 	 	 
	$year_ep=$row_Recordset1[year_ep];	  
   	} while ($row_Recordset1 = mysql_fetch_assoc($Recordset1)); 
 #ค่ารวมทั้งหมด  AcctOutputOctets
    $query_Recordset1 = "SELECT COUNT( radacct.UserName ) AS data_Upload, DATE_FORMAT( radacct.AcctStartTime,  '%d-%m-%Y' ) AS times
FROM radacct
WHERE radacct.AcctStartTime
BETWEEN  ' $year_gp-$mountgp-$daygp 00:00:00'
AND  '$year_ep-$mountep-$dayep 00:00:00'
and UserName in ( select UserName from register  where domain='$domain_name' )
GROUP BY times ";
$Recordset1 = mysql_query($query_Recordset1, $connect_db) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);
$datas=0;
 $a=1;
 
   do {  
  //ใส่ค่าความสูงราฟ
 
 
  $bar_red->data[] =$row_Recordset1[data_Upload];
  $UserNamebar[$a]=$row_Recordset1[times];
  $a++;
  $datas=$row_Recordset1[data_Upload]+$datas;
  	} while ($row_Recordset1 = mysql_fetch_assoc($Recordset1));  

 
  
# create the graph object:
$g = new graph();
$g->title( 'Online Bar Chart  of  MONTH ', '{font-size:20px; color: #FFFFFF; margin: 5px; background-color: #505050; padding:5px; padding-left: 20px; padding-right: 20px;}' );
$g->data_sets[] = $bar_red;
$g->set_x_axis_3d( 12 );
$g->x_axis_colour( '#909090', '#ADB5C7' );
$g->y_axis_colour( '#909090', '#ADB5C7' );
 
 if($totalRows_Recordset1==1 ) {  
 $g->set_x_labels( array( $UserNamebar[1])); 
 }
  if($totalRows_Recordset1==2 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2])  ); 
 }
   if($totalRows_Recordset1==3 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2],$UserNamebar[3])  ); 
 }
 
   if($totalRows_Recordset1==4 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3],$UserNamebar[4])  ); 
 } 
   if($totalRows_Recordset1==5 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5])  ); 
 }  
   if($totalRows_Recordset1==6 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6])  ); 
 }  
    if($totalRows_Recordset1==7 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7])  ); 
 }
     if($totalRows_Recordset1==8 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8])  ); 
 }
     if($totalRows_Recordset1==9 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9])  ); 
 }

     if($totalRows_Recordset1==10 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10])  ); 
 }
      if($totalRows_Recordset1==11 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11])  ); 
 } 
      if($totalRows_Recordset1==12 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12])  ); 
 }  
      if($totalRows_Recordset1==13 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13])  ); 
 }  
       if($totalRows_Recordset1==14 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14])  ); 
 } 
        if($totalRows_Recordset1==15 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15])  ); 
 } 
 
         if($totalRows_Recordset1==16 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16])  ); 
 } 
          if($totalRows_Recordset1==17 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17])  ); 
 } 
           if($totalRows_Recordset1==18 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18])  ); 
 } 
 
            if($totalRows_Recordset1==19 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19])  ); 
 } 
            if($totalRows_Recordset1==20 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20])  ); 
 }  
             if($totalRows_Recordset1==21 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21])  ); 
 } 
              if($totalRows_Recordset1==22 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22])  ); 
 } 
               if($totalRows_Recordset1==23 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23])  ); 
 } 
               if($totalRows_Recordset1==24 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24])  ); 
 }  
                if($totalRows_Recordset1==25 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25])  ); 
 }  
 
                 if($totalRows_Recordset1==26 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26])  ); 
 }  
 
                  if($totalRows_Recordset1==27 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27])  ); 
 }  
                  if($totalRows_Recordset1==28 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28])  ); 
 }   
                  if($totalRows_Recordset1==29 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29])  ); 
 }   
                   if($totalRows_Recordset1==30 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30])  ); 
 }   
                    if($totalRows_Recordset1==31 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[31])  ); 
 }   
                     if($totalRows_Recordset1==32 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32])  ); 
 }  
                      if($totalRows_Recordset1==33 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33])  ); 
 } 

                      if($totalRows_Recordset1==34 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34])  ); 
 } 
                       if($totalRows_Recordset1==35 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35])  ); 
 }  
                        if($totalRows_Recordset1==36 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36])  ); 
 }  
                         if($totalRows_Recordset1==37 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37])  ); 
 }  
                          if($totalRows_Recordset1==38 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38])  ); 
 }  
 
                           if($totalRows_Recordset1==39 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39])  ); 
 }  
                           if($totalRows_Recordset1==40 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40])  ); 
 }  
                            if($totalRows_Recordset1==41 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41])  ); 
 }  
                            if($totalRows_Recordset1==42 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42])  ); 
 }    
                             if($totalRows_Recordset1==43 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43])  ); 
 }    
                              if($totalRows_Recordset1==44 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44])  ); 
 }    
                                 if($totalRows_Recordset1==45 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45])  ); 
 }  
                                if($totalRows_Recordset1==46 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46])  ); 
 }  
                                if($totalRows_Recordset1==47 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47])  ); 
 }   
                                 if($totalRows_Recordset1==48 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48])  ); 
 }  
                                  if($totalRows_Recordset1==49 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49])  ); 
 }
                                   if($totalRows_Recordset1==50 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50])  ); 
 }  
 
                                     if($totalRows_Recordset1==51 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51])  ); 
 }  
                                      if($totalRows_Recordset1==52 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52])  ); 
 }  
                                      if($totalRows_Recordset1==53 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53])  ); 
 }   
 
                                       if($totalRows_Recordset1==54 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54])  ); 
 } 
 
                                        if($totalRows_Recordset1==55 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55])  ); 
 } 
                                         if($totalRows_Recordset1==56 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56])  ); 
 } 
                                         if($totalRows_Recordset1==57 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57])  ); 
 } 
                                           if($totalRows_Recordset1==58 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58])  ); 
 } 
                                           if($totalRows_Recordset1==59 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59])  ); 
 } 
                                            if($totalRows_Recordset1==60 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60])  ); 
 } 
                                             if($totalRows_Recordset1==61 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61])  ); 
 } 
                                              if($totalRows_Recordset1==62 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62])  ); 
 } 
                                               if($totalRows_Recordset1==63 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63])  ); 
 } 
                                                if($totalRows_Recordset1==64 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64])  ); 
 } 
                                                 if($totalRows_Recordset1==65 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65])  ); 
 } 
 
                                               if($totalRows_Recordset1==66 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66])  ); 
 } 
                                                if($totalRows_Recordset1==67 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67])  ); 
 } 
 
                                                 if($totalRows_Recordset1==68 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68])  ); 
 } 
                                                  if($totalRows_Recordset1==69 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69])  ); 
 } 
                                                   if($totalRows_Recordset1==70 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70])  ); 
 } 
                                                    if($totalRows_Recordset1==71 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71])  ); 
 } 
                                                     if($totalRows_Recordset1==72 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72])  ); 
 } 
 
                                                      if($totalRows_Recordset1==73 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73])  ); 
 } 
                                                      if($totalRows_Recordset1==74 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74])  ); 
 } 
 
                                                       if($totalRows_Recordset1==75 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75])  ); 
 } 
 
                                                        if($totalRows_Recordset1==76 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76])  ); 
 } 
 
                                                         if($totalRows_Recordset1==77 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77])  ); 
 } 
                                                          if($totalRows_Recordset1==78 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78])  ); 
 }
                                                           if($totalRows_Recordset1==79 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79])  ); 
 }
                                                            if($totalRows_Recordset1==80 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80])  ); 
 }
                                                             if($totalRows_Recordset1==81 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81])  ); 
 }
                                                        if($totalRows_Recordset1==82 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81],$UserNamebar[82])  ); 
 }
                                                         if($totalRows_Recordset1==83 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81],$UserNamebar[82],$UserNamebar[83])  ); 
 }
                                                          if($totalRows_Recordset1==84 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81],$UserNamebar[82],$UserNamebar[83],$UserNamebar[84])  ); 
 }
                                                           if($totalRows_Recordset1==85 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81],$UserNamebar[82],$UserNamebar[83],$UserNamebar[84],$UserNamebar[85])  ); 
 }
 
                                                            if($totalRows_Recordset1==86 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81],$UserNamebar[82],$UserNamebar[83],$UserNamebar[84],$UserNamebar[85],$UserNamebar[86])  ); 
 }
                                                             if($totalRows_Recordset1==87 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81],$UserNamebar[82],$UserNamebar[83],$UserNamebar[84],$UserNamebar[85],$UserNamebar[86],$UserNamebar[87])  ); 
 }
 
                                                              if($totalRows_Recordset1==88 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81],$UserNamebar[82],$UserNamebar[83],$UserNamebar[84],$UserNamebar[85],$UserNamebar[86],$UserNamebar[87],$UserNamebar[88])  ); 
 }
                                                               if($totalRows_Recordset1==89 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81],$UserNamebar[82],$UserNamebar[83],$UserNamebar[84],$UserNamebar[85],$UserNamebar[86],$UserNamebar[87],$UserNamebar[88],$UserNamebar[89])  ); 
 }
                                                                if($totalRows_Recordset1==90 ) {  
 $g->set_x_labels( array( $UserNamebar[1],$UserNamebar[2] ,$UserNamebar[3] ,$UserNamebar[4],$UserNamebar[5],$UserNamebar[6],$UserNamebar[7],$UserNamebar[8],$UserNamebar[9],$UserNamebar[10],$UserNamebar[11],$UserNamebar[12],$UserNamebar[13],$UserNamebar[14],$UserNamebar[15],$UserNamebar[16],$UserNamebar[17],$UserNamebar[18],$UserNamebar[19],$UserNamebar[20],$UserNamebar[21],$UserNamebar[22],$UserNamebar[23],$UserNamebar[24],$UserNamebar[25],$UserNamebar[26],$UserNamebar[27],$UserNamebar[28],$UserNamebar[29],$UserNamebar[30],$UserNamebar[32],$UserNamebar[33],$UserNamebar[34],$UserNamebar[35],$UserNamebar[36],$UserNamebar[37],$UserNamebar[38],$UserNamebar[39],$UserNamebar[40],$UserNamebar[41],$UserNamebar[42],$UserNamebar[43],$UserNamebar[44],$UserNamebar[45],$UserNamebar[46],$UserNamebar[47],$UserNamebar[48],$UserNamebar[49],$UserNamebar[50],$UserNamebar[51],$UserNamebar[52],$UserNamebar[53],$UserNamebar[54],$UserNamebar[55],$UserNamebar[56],$UserNamebar[57],$UserNamebar[58],$UserNamebar[59],$UserNamebar[60],$UserNamebar[61],$UserNamebar[62],$UserNamebar[63],$UserNamebar[64],$UserNamebar[65],$UserNamebar[66],$UserNamebar[67],$UserNamebar[68],$UserNamebar[69],$UserNamebar[70],$UserNamebar[71],$UserNamebar[72],$UserNamebar[73],$UserNamebar[74],$UserNamebar[75],$UserNamebar[76],$UserNamebar[77],$UserNamebar[78],$UserNamebar[79],$UserNamebar[80],$UserNamebar[81],$UserNamebar[82],$UserNamebar[83],$UserNamebar[84],$UserNamebar[85],$UserNamebar[86],$UserNamebar[87],$UserNamebar[88],$UserNamebar[89],$UserNamebar[90])  ); 
 }
$g->set_y_max( $datas );
$g->y_label_steps( 5 );
$g->set_y_legend( 'Thaigqsoft.com', 12, '#736AFF' );
echo $g->render();


?>


</body>
</html>
